#!/usr/bin/env python3
"""SPECTRUM — generate and verify the G4-WATCH colour system.

The palette is not hand-picked. Every colour is specified in OKLCH, where
lightness is perceptually uniform, and generated by rule; this file is the
source of truth and ``web/workstation/static/spectrum.css`` is its output.
Editing the CSS by hand will be overwritten.

WHY OKLCH: two swatches with the same L look equally bright regardless of
hue. That is what lets a categorical palette carry twelve lineages without
one of them visually shouting, and it is what makes "confidence is chroma"
a legible rule rather than a slogan.

THE DERIVATION: the workflow accents are the emission wavelengths of the
fluorophores and laser lines that this data was actually read with --
405 nm violet diode, Pacific Blue, the 488 argon line, FAM, HEX, TAMRA,
ROX, Cy5. The pipeline therefore runs along the spectrum in the order a
sequencer reads it. This is the identity: the instrument's own spectrum.

Run:  python scripts/design/spectrum.py --write
"""

from __future__ import annotations

import argparse
import json
import math
from dataclasses import dataclass
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
CSS_OUT = REPO / "web/workstation/static/spectrum.css"
JSON_OUT = REPO / "web/workstation/static/spectrum.json"


# ══ colour maths ════════════════════════════════════════════════════
def _srgb_encode(c: float) -> float:
    c = max(0.0, min(1.0, c))
    return 12.92 * c if c <= 0.0031308 else 1.055 * (c ** (1 / 2.4)) - 0.055


def _srgb_decode(c: float) -> float:
    return c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4


def oklch_to_linear(L: float, C: float, h_deg: float) -> tuple[float, float, float]:
    h = math.radians(h_deg)
    a, b = C * math.cos(h), C * math.sin(h)
    l_ = (L + 0.3963377774 * a + 0.2158037573 * b) ** 3
    m_ = (L - 0.1055613458 * a - 0.0638541728 * b) ** 3
    s_ = (L - 0.0894841775 * a - 1.2914855480 * b) ** 3
    return (
        +4.0767416621 * l_ - 3.3077115913 * m_ + 0.2309699292 * s_,
        -1.2684380046 * l_ + 2.6097574011 * m_ - 0.3413193965 * s_,
        -0.0041960863 * l_ - 0.7034186147 * m_ + 1.7076147010 * s_,
    )


def in_gamut(rgb: tuple[float, float, float]) -> bool:
    return all(-1e-4 <= c <= 1 + 1e-4 for c in rgb)


def oklch(L: float, C: float, h: float) -> str:
    """Hex for an OKLCH triple, reducing chroma until it fits sRGB.

    Clipping chroma rather than clipping channels preserves both the hue
    and the lightness, so a colour forced into gamut still sits on its
    row of the palette.
    """
    lo, hi = 0.0, C
    if not in_gamut(oklch_to_linear(L, C, h)):
        for _ in range(40):
            mid = (lo + hi) / 2
            if in_gamut(oklch_to_linear(L, mid, h)):
                lo = mid
            else:
                hi = mid
        C = lo
    r, g, b = oklch_to_linear(L, C, h)
    return "#" + "".join(f"{round(_srgb_encode(c) * 255):02X}" for c in (r, g, b))


def hex_to_linear(hex_str: str) -> tuple[float, float, float]:
    h = hex_str.lstrip("#")
    return tuple(_srgb_decode(int(h[i : i + 2], 16) / 255) for i in (0, 2, 4))  # type: ignore[return-value]


def relative_luminance(hex_str: str) -> float:
    r, g, b = hex_to_linear(hex_str)
    return 0.2126 * r + 0.7152 * g + 0.0722 * b


def contrast(fg: str, bg: str) -> float:
    a, b = relative_luminance(fg), relative_luminance(bg)
    lo, hi = min(a, b), max(a, b)
    return (hi + 0.05) / (lo + 0.05)


def linear_to_oklab(r: float, g: float, b: float) -> tuple[float, float, float]:
    l_ = (0.4122214708 * r + 0.5363325363 * g + 0.0514459929 * b) ** (1 / 3)
    m_ = (0.2119034982 * r + 0.6806995451 * g + 0.1073969566 * b) ** (1 / 3)
    s_ = (0.0883024619 * r + 0.2817188376 * g + 0.6299787005 * b) ** (1 / 3)
    return (
        0.2104542553 * l_ + 0.7936177850 * m_ - 0.0040720468 * s_,
        1.9779984951 * l_ - 2.4285922050 * m_ + 0.4505937099 * s_,
        0.0259040371 * l_ + 0.7827717662 * m_ - 0.8086757660 * s_,
    )


# Machado et al. (2009), severity 1.0, applied in linear RGB.
CVD = {
    "protanopia": ((0.152286, 1.052583, -0.204868), (0.114503, 0.786281, 0.099216), (-0.003882, -0.048116, 1.051998)),
    "deuteranopia": ((0.367322, 0.860646, -0.227968), (0.280085, 0.672501, 0.047413), (-0.011820, 0.042940, 0.968881)),
    "tritanopia": ((1.255528, -0.076749, -0.178779), (-0.078411, 0.930809, 0.147602), (0.004733, 0.691367, 0.303900)),
}


def simulate(hex_str: str, kind: str) -> tuple[float, float, float]:
    r, g, b = hex_to_linear(hex_str)
    m = CVD[kind]
    return tuple(max(0.0, min(1.0, m[i][0] * r + m[i][1] * g + m[i][2] * b)) for i in range(3))  # type: ignore[return-value]


def delta_e(a_lin, b_lin) -> float:
    """Euclidean distance in OKLab: a serviceable perceptual difference."""
    la, aa, ba = linear_to_oklab(*a_lin)
    lb, ab, bb = linear_to_oklab(*b_lin)
    return math.dist((la, aa, ba), (lb, ab, bb))


# ══ the system ══════════════════════════════════════════════════════
# One hue anchors the whole interface: 214 deg, a blue-green graphite.
# Every neutral carries a trace of it, so the greys read as chosen rather
# than as the absence of a decision.
NEUTRAL_HUE = 214

# Measured, not assumed. A farthest-point search over the OKLCH solid,
# scored under normal vision and all three dichromacies, yields these
# worst-case separations:
#
#     n     normal  protan  deuter  tritan
#     6      0.142   0.105   0.105   0.105
#     8      0.099   0.093   0.091   0.092     <- colour alone is safe
#    10      0.080   0.064   0.059   0.059
#    12      0.059   0.049   0.047   0.047     <- needs a second channel
#
# So eight is the honest limit for colour-only categorical encoding. The
# extended twelve exists, but the system's rules forbid using it without
# a second encoding channel (shape, texture, or a direct label).
CORE_N = 8
EXTENDED_N = 12
CORE_FLOOR = {"normal": 0.095, "cvd": 0.085}

# Hues reserved for meaning. No categorical data colour may occupy them,
# which is why a lineage can never be mistaken for an error.
RESERVED = {
    "running": 232,
    "complete": 152,
    "warning": 78,
    "error": 28,
    "significant": 342,
    "recombination": 305,
}


@dataclass(frozen=True)
class Stage:
    key: str
    label: str
    nm: int
    source: str
    hue: float


# The pipeline, ordered by the emission wavelength it is named for.
WORKFLOW = [
    Stage("data", "Data", 405, "405 nm violet diode", 288),
    Stage("qc", "Quality control", 455, "Pacific Blue", 258),
    Stage("genomic", "Genomic analysis", 488, "488 nm argon line", 225),
    Stage("evolution", "Evolutionary analysis", 517, "FAM / fluorescein", 168),
    Stage("network", "Network analysis", 553, "HEX / JOE", 138),
    Stage("model", "Modelling", 583, "TAMRA", 96),
    Stage("interpret", "Interpretation", 607, "ROX", 58),
    Stage("report", "Reporting", 670, "Cy5", 26),
]


def backgrounds(dark: bool) -> dict[str, str]:
    """Seven working depths, spaced by perceptual lightness, not opacity.

    LIGHT IS THE BASE. Every tool a genomicist actually reads all day --
    Nextstrain, IGV, the UCSC browser, Geneious, Cytoscape, Prism, any
    ggplot output -- is light, and every figure exported from this one
    lands on white paper. Dark is a code-editor convention borrowed into
    product design; it is offered here as an option, not as the identity.

    The light ramp is built as a journal page rather than as an inverted
    dark theme: the canvas is the near-white figure panel, the workspace
    is the page around it, and chrome sinks *below* both. Dark inverts
    that relationship, sinking the canvas so dense marks float clear.
    """
    h, c = NEUTRAL_HUE, 0.014 if dark else 0.005
    steps = (
        # name        dark    light
        ("void", 0.128, 0.902),
        ("canvas", 0.163, 0.995),
        ("workspace", 0.201, 0.970),
        ("surface", 0.237, 0.948),
        ("panel", 0.271, 1.000),
        ("hover", 0.309, 0.928),
        ("select", 0.351, 0.902),
    )
    return {name: oklch(d if dark else lt, c, h) for name, d, lt in steps}


def text(dark: bool) -> dict[str, str]:
    steps = (
        ("primary", 0.962, 0.205),
        ("secondary", 0.800, 0.372),
        ("tertiary", 0.646, 0.492),
        ("quaternary", 0.512, 0.602),
        ("disabled", 0.416, 0.688),
    )
    c = 0.006
    return {name: oklch(d if dark else lt, c, NEUTRAL_HUE) for name, d, lt in steps}


def lines(dark: bool) -> dict[str, str]:
    steps = (("hairline", 0.238, 0.905), ("rule", 0.292, 0.855), ("edge", 0.372, 0.780))
    return {name: oklch(d if dark else lt, 0.012, NEUTRAL_HUE) for name, d, lt in steps}


def workflow(dark: bool) -> dict[str, dict[str, str]]:
    """Two chroma levels per stage. Resting is nearly neutral; active is
    the real hue. Progression is legible without eight shouting colours."""
    L = 0.760 if dark else 0.520
    out = {}
    for stage in WORKFLOW:
        out[stage.key] = {
            "rest": oklch(L * (0.72 if dark else 1.06), 0.035, stage.hue),
            "active": oklch(L, 0.142, stage.hue),
            "wash": oklch(0.238 if dark else 0.940, 0.040 if dark else 0.038, stage.hue),
            "nm": str(stage.nm),
            "source": stage.source,
            "label": stage.label,
        }
    return out


def status(dark: bool) -> dict[str, str]:
    L = 0.760 if dark else 0.505
    out = {
        "complete": oklch(L, 0.125, RESERVED["complete"]),
        "running": oklch(L, 0.130, RESERVED["running"]),
        "pending": oklch(0.560 if dark else 0.600, 0.010, NEUTRAL_HUE),
        "warning": oklch(L, 0.138, RESERVED["warning"]),
        "error": oklch(L, 0.155, RESERVED["error"]),
        "significant": oklch(L, 0.165, RESERVED["significant"]),
        "emerging": oklch(L, 0.150, 44),
    }
    # Confidence is not a hue. It is the chroma any finding is drawn at,
    # so a result never changes colour when its support changes -- it
    # only becomes more or less insistent.
    out["confidence-high"] = oklch(L, 0.150, RESERVED["significant"])
    out["confidence-medium"] = oklch(L, 0.075, RESERVED["significant"])
    out["confidence-low"] = oklch(L, 0.030, RESERVED["significant"])
    for name in ("complete", "running", "warning", "error", "significant", "emerging"):
        h = RESERVED.get(name, 44)
        out[name + "-wash"] = oklch(0.242 if dark else 0.945, 0.045 if dark else 0.042, h)
    return out


def _vision_vectors(hex_str: str) -> list[tuple[float, float, float]]:
    """The colour as normal vision and as each dichromacy sees it."""
    return [
        linear_to_oklab(*hex_to_linear(hex_str)),
        *(linear_to_oklab(*simulate(hex_str, k)) for k in CVD),
    ]


def _worst_gap(a: list, b: list) -> float:
    """Separation between two colours under the least favourable vision."""
    return min(math.dist(x, y) for x, y in zip(a, b))


def categorical(dark: bool, n: int = 12) -> list[str]:
    """Twelve lineage colours, chosen by farthest-point search.

    Hue alone fails past about eight categories, and fails immediately
    under deuteranopia. So the candidate space varies lightness as well as
    hue, and selection maximises the *minimum* separation measured
    simultaneously under normal vision and all three dichromacies. The
    palette is therefore not a designer's hue wheel: it is the most
    separable twelve points that survive every viewer.

    Hues within 14 deg of the significant-finding and recombination
    anchors are excluded, so those two meanings stay unambiguous.
    """
    bands = (
        ((0.900, 0.065), (0.800, 0.115), (0.680, 0.135), (0.560, 0.130))
        if dark
        else ((0.700, 0.080), (0.590, 0.110), (0.470, 0.135), (0.360, 0.130))
    )

    def blocked(hue: float) -> bool:
        for anchor in (RESERVED["significant"], RESERVED["recombination"]):
            if abs((hue - anchor + 180) % 360 - 180) < 14:
                return True
        return False

    candidates = []
    for hue in range(0, 360, 5):
        if blocked(hue):
            continue
        for L, C in bands:
            hexv = oklch(L, C, hue)
            candidates.append((hexv, _vision_vectors(hexv)))

    # Precompute worst-case separation once; the greedy search then only
    # reads the matrix, which makes an all-seeds sweep affordable.
    m = len(candidates)
    gap = [[0.0] * m for _ in range(m)]
    for i in range(m):
        for j in range(i + 1, m):
            g = _worst_gap(candidates[i][1], candidates[j][1])
            gap[i][j] = gap[j][i] = g

    best: tuple[float, list[int]] = (-1.0, [])
    for seed in range(m):
        chosen = [seed]
        near = list(gap[seed])
        for _ in range(n - 1):
            pick = max((i for i in range(m) if i not in chosen), key=lambda i: near[i])
            chosen.append(pick)
            row = gap[pick]
            near = [min(near[i], row[i]) for i in range(m)]
        score = min(gap[a][b] for x, a in enumerate(chosen) for b in chosen[x + 1 :])
        if score > best[0]:
            best = (score, list(chosen))

    picked = [candidates[i][0] for i in best[1]]
    # Order by hue so the legend reads as a spectrum rather than a scatter.
    picked.sort(key=lambda h: linear_to_oklab(*hex_to_linear(h))[2])
    return picked


def diverging(dark: bool, n: int = 9) -> list[str]:
    """Selection pressure is signed data: dN/dS below 1, at 1, above 1.

    A diverging ramp with a genuinely neutral midpoint, so 'no detectable
    selection' is not accidentally coloured as a finding.
    """
    cool, warm = 232, 28
    out = []
    for i in range(n):
        t = i / (n - 1) * 2 - 1
        hue = cool if t < 0 else warm
        C = abs(t) * 0.145
        L = (0.560 if dark else 0.500) + (1 - abs(t)) * (0.190 if dark else 0.330)
        out.append(oklch(L, C, hue))
    return out


def sequential(dark: bool, hue: float, n: int = 9) -> list[str]:
    """Single-hue ramp for magnitude: diversity, coverage, density."""
    out = []
    for i in range(n):
        t = i / (n - 1)
        L = (0.220 + t * 0.700) if dark else (0.960 - t * 0.660)
        C = 0.030 + t * 0.115 if dark else 0.025 + t * 0.130
        out.append(oklch(L, C, hue))
    return out


def biology(dark: bool) -> dict[str, str]:
    L = 0.760 if dark else 0.500
    return {
        "mutation": oklch(L, 0.150, RESERVED["error"]),
        "mutation-synonymous": oklch(L, 0.045, RESERVED["error"]),
        "clade": oklch(L, 0.100, 196),
        "gene": oklch(0.640 if dark else 0.620, 0.030, NEUTRAL_HUE),
        "selection-positive": oklch(L, 0.145, 28),
        "selection-negative": oklch(L, 0.145, 232),
        "selection-neutral": oklch(0.560 if dark else 0.600, 0.008, NEUTRAL_HUE),
        "recombination": oklch(L, 0.140, RESERVED["recombination"]),
        "diversity-high": oklch(L, 0.130, 168),
        "diversity-low": oklch(0.400 if dark else 0.790, 0.028, 168),
        "emerging-variant": oklch(L, 0.150, 44),
        "outlier": oklch(0.930 if dark else 0.300, 0.055, RESERVED["significant"]),
        "reference": oklch(0.930 if dark else 0.240, 0.004, NEUTRAL_HUE),
        "gap": oklch(0.330 if dark else 0.860, 0.006, NEUTRAL_HUE),
    }


def build(dark: bool) -> dict:
    return {
        "background": backgrounds(dark),
        "text": text(dark),
        "line": lines(dark),
        "workflow": workflow(dark),
        "status": status(dark),
        "categorical": categorical(dark, CORE_N),
        "categorical_extended": categorical(dark, EXTENDED_N),
        "diverging": diverging(dark),
        "sequential_diversity": sequential(dark, 168),
        "sequential_density": sequential(dark, 232),
        "biology": biology(dark),
    }


# ══ verification ════════════════════════════════════════════════════
def verify(spec: dict, dark: bool) -> list[str]:
    problems: list[str] = []
    label = "dark" if dark else "light"
    bg = spec["background"]["workspace"]
    canvas = spec["background"]["canvas"]

    for name, need in (("primary", 7.0), ("secondary", 4.5), ("tertiary", 3.0), ("quaternary", 2.2)):
        ratio = contrast(spec["text"][name], bg)
        if ratio < need:
            problems.append(f"{label}: text.{name} on workspace = {ratio:.2f}:1, want >= {need}")

    for name, hexv in spec["status"].items():
        if name.endswith("-wash") or name.startswith("confidence-"):
            continue
        ratio = contrast(hexv, bg)
        if ratio < 3.0:
            problems.append(f"{label}: status.{name} on workspace = {ratio:.2f}:1, want >= 3.0")

    for palette, enforce in (("categorical", True), ("categorical_extended", False)):
        cats = spec[palette]
        for kind in ("normal", *CVD):
            sims = [hex_to_linear(c) if kind == "normal" else simulate(c, kind) for c in cats]
            worst, pair = 1e9, None
            for i in range(len(cats)):
                for j in range(i + 1, len(cats)):
                    d = delta_e(sims[i], sims[j])
                    if d < worst:
                        worst, pair = d, (i, j)
            floor = CORE_FLOOR["normal" if kind == "normal" else "cvd"]
            line = f"{label}: {palette}[{len(cats)}] min deltaE ({kind}) = {worst:.3f}  (#{pair[0]}/#{pair[1]})"
            if enforce and worst < floor:
                problems.append(line + f" -- below floor {floor}")
            elif enforce:
                print("   ok  " + line)
            else:
                print("   fyi " + line + "  [dual-encoding required]")

    cats = spec["categorical"]
    for i, c in enumerate(cats):
        ratio = contrast(c, canvas)
        if ratio < 2.4:
            problems.append(f"{label}: categorical[{i}] on canvas = {ratio:.2f}:1, want >= 2.4")

    for stage_key, stage in spec["workflow"].items():
        ratio = contrast(stage["active"], bg)
        if ratio < 3.0:
            problems.append(f"{label}: workflow.{stage_key}.active on workspace = {ratio:.2f}:1")

    return problems


# ══ emit ════════════════════════════════════════════════════════════
def to_css(dark_spec: dict, light_spec: dict) -> str:
    def block(spec: dict, indent: str) -> str:
        out = []
        for group in ("background", "text", "line"):
            for k, v in spec[group].items():
                prefix = {"background": "bg", "text": "text", "line": "line"}[group]
                out.append(f"{indent}--{prefix}-{k}: {v};")
        for key, stage in spec["workflow"].items():
            for variant in ("rest", "active", "wash"):
                out.append(f"{indent}--flow-{key}-{variant}: {stage[variant]};")
        for k, v in spec["status"].items():
            out.append(f"{indent}--st-{k}: {v};")
        for i, c in enumerate(spec["categorical"]):
            out.append(f"{indent}--cat-{i}: {c};")
        for i, c in enumerate(spec["categorical_extended"]):
            out.append(f"{indent}--catx-{i}: {c};")
        for i, c in enumerate(spec["diverging"]):
            out.append(f"{indent}--div-{i}: {c};")
        for i, c in enumerate(spec["sequential_diversity"]):
            out.append(f"{indent}--seq-div-{i}: {c};")
        for i, c in enumerate(spec["sequential_density"]):
            out.append(f"{indent}--seq-den-{i}: {c};")
        for k, v in spec["biology"].items():
            out.append(f"{indent}--bio-{k}: {v};")
        return "\n".join(out)

    return f"""/* SPECTRUM — generated by scripts/design/spectrum.py. Do not edit by hand.
 *
 * Accent hues are the emission wavelengths this data was read with:
 * 405 nm diode, Pacific Blue, the 488 argon line, FAM, HEX, TAMRA, ROX,
 * Cy5 -- so the pipeline runs along the spectrum in reading order.
 *
 * LIGHT IS THE BASE. The tools a genomicist reads all day are light, and
 * every figure exported from this one lands on white paper. Dark is
 * offered for long visualisation sessions; it is the variant, not the
 * identity.
 */

:root {{
{block(light_spec, "  ")}
}}

@media (prefers-color-scheme: dark) {{
  :root:not([data-theme="light"]) {{
{block(dark_spec, "    ")}
  }}
}}

:root[data-theme="dark"] {{
{block(dark_spec, "  ")}
}}
"""


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true", help="write the CSS and JSON outputs")
    args = ap.parse_args()

    dark, light = build(True), build(False)

    print("SPECTRUM verification")
    problems = verify(dark, True) + verify(light, False)
    if problems:
        print("\nPROBLEMS")
        for p in problems:
            print("  !! " + p)
    else:
        print("\n   all contrast and colour-vision checks passed")

    if args.write:
        CSS_OUT.parent.mkdir(parents=True, exist_ok=True)
        CSS_OUT.write_text(to_css(dark, light))
        JSON_OUT.write_text(json.dumps({"dark": dark, "light": light}, indent=1))
        print(f"\n   wrote {CSS_OUT.relative_to(REPO)}")
        print(f"   wrote {JSON_OUT.relative_to(REPO)}")

    return 1 if problems else 0


if __name__ == "__main__":
    raise SystemExit(main())
